### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'score'

### ISSUE THREAD

**Issue by SwiftGodDev** [ginop/reconchess-strangefish#1]
I am trying to run this on google colab using conda. Everytime i run it, it connects to  the server but gives the error in the title.

18974 03:54:59  🦋  Connected successfully to server!
18985 03:55:26  🌺  Invitation 347768 accepted. Playing game 186598.
18985 03:55:26  🌺  Starting a new game as black against StrangeFish2.
18985 03:55:27  🌺  Playing turn  1. (900 seconds left.)
18985 03:55:29  🌺     Done turn  1.
Process Process-1:8:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/content/drive/My Drive/reconchess-strangefish/strangefish/multiprocessing_strategies.py", line 185, in worker
    engine=engine, score_config=score_config)
  File "/content/drive/My Drive/reconchess-strangefish/strangefish/rbc_move_score.py", line 48, in calculate_score
    score = engine_result.score.pov(pov).score(mate_score=score_config.checkmate_score)
AttributeError: 'dict' object has no attribute 'score'

**Comment by ginop** [comment]
Ah, yep, I see it.

python-chess no longer uses the same data structure it did when this was written. The attributes cannot be accessed as `engine_result.score`, instead it needs to be `engine_result['score']`. The remainder of that line still works the same way.

I'll need to check for other locations that the same change affects, although it may just be that one. Feel free to make a pull request if you get around to it first!

**Comment by ginop** [comment]
Brief testing shows games working as expected after making the above change. Update pushed! Issue will be closed as fixed; let me know if your result is different.
