### ISSUE TITLE
Cannot import ranked_mode

### ISSUE THREAD

**Issue by SwiftGodDev** [ginop/reconchess-strangefish#2]
Traceback (most recent call last):
  File "modified_rc_connect.py", line 12, in <module>
    from reconchess.scripts.rc_connect import RBCServer, ranked_mode, unranked_mode, check_package_version
ImportError: cannot import name 'ranked_mode'

**Comment by ginop** [comment]
I see this is closed, but in case other users have this problem later: was it just that the reconchess library needed to be updated?

**Comment by SwiftGodDev** [comment]
I just installed the latest reconchess library and it worked.

**Comment by SwiftGodDev** [comment]
And also please add latest version of PyYAML
